"""C++ emission for the IFE code generator.

Output is byte-stable: deterministic ordering (JSON document order for
blocks and groups, version-ascending for field groups) and no timestamps,
so CI can diff-check regeneration.
"""
from __future__ import annotations

from typing import Any

from ..model.layout import FieldLayout, LayoutResult, SpecError, _TYPE_CPP, _canonical_type, is_banner, parse_int, version_key

BANNER = """\
// =============================================================================
// THIS FILE IS GENERATED BY generator/ (python -m generator) — DO NOT EDIT BY HAND.
// Source schema: spec/ife_fields.json + spec/ife_constants.json
// Regenerate with:
//     python3 -m generator
// =============================================================================
"""


def _pascal(name: str) -> str:
    """snake_case -> PascalCase for enum class names."""
    return "".join(part.capitalize() for part in name.split("_"))


def _value_display(value: Any) -> str:
    """Keep hex constants as authored (0x...); render ints as decimal."""
    if isinstance(value, str) and value.lower().startswith("0x"):
        return value
    return str(parse_int(value))


def _cpp_of(type_name: str, types: dict[str, Any]) -> str:
    canonical = _canonical_type(type_name, types)
    try:
        return _TYPE_CPP[canonical]
    except KeyError:
        raise SpecError(f"type {type_name!r} resolves to unsupported canonical {canonical!r}") from None


def _comment(text: str, prefix: str = "//") -> list[str]:
    """Multi-line comment block; blank lines are dropped."""
    return [f"{prefix} {line}" for line in text.splitlines() if line.strip()] if text else []


def emit_constants_header(doc: dict[str, Any], types: dict[str, Any]) -> str:
    """IFE_Constants.hpp — enums + statically defined sentinel values."""
    spec = doc.get("spec", {})
    version = spec.get("version", {})
    out: list[str] = [
        BANNER,
        "#ifndef IFE_Constants_hpp",
        "#define IFE_Constants_hpp",
        "",
        "#include <cstdint>",
        "",
        "namespace IFE {",
        f"inline constexpr unsigned IFE_SCHEMA_VERSION_MAJOR = {version.get('major', 0)};",
        f"inline constexpr unsigned IFE_SCHEMA_VERSION_MINOR = {version.get('minor', 0)};",
        "",
        "namespace constants {",
    ]

    for group_name, group in doc.items():
        if group_name in ("$schema", "spec", "statically_defined_values") or is_banner(group_name):
            continue
        underlying = group.get("underlying_type")
        if underlying is None:
            raise SpecError(f"enum group {group_name!r} has no underlying_type")
        # Resolve through the alias chain, exactly as a sentinel's "type" is
        # resolved. Looking underlying_type up in _TYPE_CPP directly made the
        # same word behave two ways: "type": "recovery" worked, while
        # "underlying_type": "recovery" raised.
        cpp = _cpp_of(underlying, types)

        members: list[tuple[str, str, str, str | None]] = []
        for _, entries in sorted(group.get("ife_version", {}).items(), key=lambda kv: version_key(kv[0])):
            for member_name, raw in entries.items():
                if isinstance(raw, dict):
                    members.append(
                        (
                            member_name,
                            _value_display(raw.get("value")),
                            str(raw.get("description", "")),
                            raw.get("errata"),
                        )
                    )
                else:
                    members.append((member_name, _value_display(raw), "", None))

        out.append("")
        out.extend(_comment(group.get("description", "")))
        out.append(f"enum class {_pascal(group_name)} : {cpp} {{")
        for member_name, display, description, errata in members:
            out.extend(_comment(description, "///"))
            if errata:
                out.extend(_comment(f"errata: {errata}"))
            out.append(f"    {member_name} = {display},")
        out.append("};")

    out.append("")
    out.append("// Statically defined values (sentinel constants)")
    sentinels = doc.get("statically_defined_values", {}).get("ife_version", {})
    for _, entries in sorted(sentinels.items(), key=lambda kv: version_key(kv[0])):
        for name, entry in entries.items():
            out.extend(_comment(entry.get("description", ""), "///"))
            if entry.get("errata"):
                out.extend(_comment(f"errata: {entry['errata']}"))
            out.append(f"inline constexpr {_cpp_of(entry['type'], types)} {name} = {_value_display(entry['value'])};")

    out += ["", "} // namespace constants", "} // namespace IFE", "", "#endif // IFE_Constants_hpp", ""]
    return "\n".join(out)


def _emit_size_offset(fields: tuple[FieldLayout, ...], indent: str = "    ") -> list[str]:
    """size{} and offset{} namespaces for a field list."""
    out = [f"{indent}namespace size {{"]
    for field in fields:
        out.extend(_comment(field.description, f"{indent}///"))
        out.append(f"{indent}    inline constexpr std::size_t {field.name} = {field.size};")
    out.append(f"{indent}}}")
    out.append(f"{indent}namespace offset {{")
    for field in fields:
        out.append(f"{indent}    inline constexpr std::size_t {field.name} = {field.offset};")
    out.append(f"{indent}}}")
    return out


def _emit_structure(
    out: list[str], namespace: str, comment: str, fields: tuple[FieldLayout, ...], total_name: str, total: int
) -> None:
    out.append(f"// ---- {comment} ----" if comment else f"// ---- {namespace} ----")
    out.append(f"namespace {namespace} {{")
    out.extend(_emit_size_offset(fields))
    out.append(f"    inline constexpr std::size_t {total_name} = {total};")
    out.append("}")


def emit_vtables_header(layout: LayoutResult) -> str:
    """IFE_VTables.hpp — derived per-block offset/size vtables."""
    out: list[str] = [
        BANNER,
        "#ifndef IFE_VTables_hpp",
        "#define IFE_VTables_hpp",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        '#include "IFE_Constants.hpp"',
        "",
        "namespace IFE {",
        "namespace vtables {",
    ]

    for primitive in layout.primitives.values():
        inherits = f" (inherits {primitive.extends})" if primitive.extends else ""
        _emit_structure(
            out, primitive.name, f"{primitive.name} primitive{inherits}",
            primitive.fields, "total_size", primitive.size,
        )
        out.append("")

    recovery_enum = _pascal("recovery_codes")
    for name, block in layout.blocks.items():
        out.append("")
        out.append(f"// ---- {name} ----")
        out.extend(_comment(block.description))
        out.append(f"namespace {name} {{")
        out.append(f"    // primitive: {block.primitive}")
        out.append(
            f"    inline constexpr ::IFE::constants::{recovery_enum} recovery_tag"
            f" = ::IFE::constants::{recovery_enum}::{block.recovery_tag};"
        )
        out.extend(_emit_size_offset(block.header_fields))
        out.append(f"    inline constexpr std::size_t header_size = {block.header_size};")
        if block.from_sof is not None:
            out.append(
                f"    /// Fixed at byte 0; occupies the first {block.from_sof} B of the file."
            )
            out.append(f"    inline constexpr std::size_t from_sof = {block.from_sof};")
        if block.entry_fields:
            if block.entry_fields:
                out.append("")
                out.append(f"    // ---- {block.entry_name} (entry, {block.entry_size} B) ----")
                out.append("    namespace entry {")
                out.extend(_emit_size_offset(block.entry_fields, indent="        "))
                out.append("    }")
                out.append("")
                out.append(f"    inline constexpr std::size_t entry_size = {block.entry_size};")
        out.append("}")

    out += ["", "} // namespace vtables", "} // namespace IFE", "", "#endif // IFE_VTables_hpp", ""]
    return "\n".join(out)
