"""C++ emission for the IFE code generator.

Output is byte-stable: deterministic ordering (JSON document order for
blocks and groups, version-ascending for field groups) and no timestamps,
so CI can diff-check regeneration. The one deliberate exception is the
copyright year range in the banner, which rolls forward at year boundaries.
"""
# ---------------------------------------------------------------------------
# ROLE: formatting only. Every function here takes a already-computed layout
# and returns a string of C++. No offset is calculated in this file — if you
# find arithmetic on a byte position here, it belongs in model/layout.py.
#
# Every emitter accumulates lines and joins once at the end. There is no
# stream and no incremental write: building each file whole, in memory, is
# what makes output byte-stable — the same layout always yields the same
# bytes, which is exactly what `--check` compares.
#
# Three public entry points, one per generated file: emit_constants_header,
# emit_vtables_header, emit_blocks_header.
# ---------------------------------------------------------------------------

from __future__ import annotations

import struct
from typing import Any, NamedTuple

from ..model.layout import RECOVERY_PREFIX, FieldLayout, LayoutResult, SpecError, _TYPE_CPP, _canonical_type, is_banner, parse_int, version_key


def _banner(document: dict[str, Any]) -> str:
    """Header comment for every generated C++ file.

    The copyright comes from spec/ife_header.json, the single place the
    specification's identity is stated. Deriving it from the clock instead
    would make generated output depend on the build date, which costs the
    byte-stability the --check gate relies on and the reproducibility a
    ratified document needs.
    """
    return f"""\
// =============================================================================
// THIS FILE IS GENERATED BY generator/ (python -m generator) — DO NOT EDIT BY HAND.
// Source schema: spec/ife_header.json + spec/ife_fields.json + spec/ife_constants.json
// {document.get('copyright', '')}
// Regenerate with:
//     python3 -m generator
// =============================================================================
"""


def _pascal(name: str) -> str:
    """snake_case -> PascalCase for enum class names."""
    return "".join(part.capitalize() for part in name.split("_"))


def _value_display(value: Any) -> str:
    """Keep hex constants as authored (0x...); render ints as decimal."""
    if isinstance(value, str) and value.lower().startswith("0x"):
        return value
    return str(parse_int(value))


def _half_literal(bits: int) -> str:
    """Decode an IEEE binary16 bit pattern into a C++ float literal.

    The spec stores half floats as their on-wire bit pattern, which is the
    right thing for a byte-layout document. Emitting that integer as a float
    constant would be silently wrong — 0x55A0 is 90.0 degrees, not 21920 —
    and the error would only surface as a comparison that never matches.
    """
    value = struct.unpack("<e", struct.pack("<H", bits))[0]
    return f"{value!r}f"


def _cpp_of(type_name: str, types: dict[str, Any]) -> str:
    canonical = _canonical_type(type_name, types)
    try:
        return _TYPE_CPP[canonical]
    except KeyError:
        raise SpecError(f"type {type_name!r} resolves to unsupported canonical {canonical!r}") from None


def _comment(text: str, prefix: str = "//") -> list[str]:
    """Multi-line comment block; blank lines are dropped."""
    return [f"{prefix} {line}" for line in text.splitlines() if line.strip()] if text else []


def emit_constants_header(
    doc: dict[str, Any], types: dict[str, Any], document: dict[str, Any]
) -> str:
    """IFE_Constants.hpp — enums + statically defined sentinel values."""
    version = document.get("version", {})
    out: list[str] = [
        _banner(document),
        "#ifndef IFE_Constants_hpp",
        "#define IFE_Constants_hpp",
        "",
        "#include <cstdint>",
        "",
        "namespace IFE {",
        f"inline constexpr unsigned IFE_SCHEMA_VERSION_MAJOR = {version.get('major', 0)};",
        f"inline constexpr unsigned IFE_SCHEMA_VERSION_MINOR = {version.get('minor', 0)};",
        "",
        "namespace constants {",
    ]

    for group_name, group in doc.items():
        if group_name in ("$schema", "spec", "statically_defined_values") or is_banner(group_name):
            continue
        underlying = group.get("underlying_type")
        if underlying is None:
            raise SpecError(f"enum group {group_name!r} has no underlying_type")
        # Resolve through the alias chain, exactly as a sentinel's "type" is
        # resolved. Looking underlying_type up in _TYPE_CPP directly made the
        # same word behave two ways: "type": "recovery" worked, while
        # "underlying_type": "recovery" raised.
        if _canonical_type(underlying, types) == "f16":
            raise SpecError(
                f"enum group {group_name!r} has underlying_type 'f16'; C++ has no "
                "'enum class : float'. A set of named values over a continuous "
                "domain belongs in statically_defined_values, not an enumeration."
            )
        cpp = _cpp_of(underlying, types)

        # Recovery tag values are derived, not authored: each is the 0x55
        # prefix plus its position. One less transcription surface, and a
        # collision becomes unrepresentable rather than merely checked.
        derived = group_name == "recovery_codes"
        members: list[tuple[str, str, str, str | None]] = []
        for _, entries in sorted(group.get("ife_version", {}).items(), key=lambda kv: version_key(kv[0])):
            for member_name, raw in entries.items():
                entry = raw if isinstance(raw, dict) else {"value": raw}
                if derived:
                    # The member states its sequence number; the generator owns
                    # the 0x55 prefix. Authoring the number rather than taking
                    # the list position means editing the list cannot silently
                    # move a tag, and the prefix is still stated exactly once.
                    if "value" not in entry:
                        raise SpecError(
                            f"recovery tag {member_name!r} states no sequence number"
                        )
                    display = f"0x{RECOVERY_PREFIX + parse_int(entry['value']):04X}"
                else:
                    display = _value_display(entry.get("value"))
                members.append(
                    (member_name, display, str(entry.get("description", "")), entry.get("errata"))
                )

        out.append("")
        out.extend(_comment(group.get("description", "")))
        out.append(f"enum class {_pascal(group_name)} : {cpp} {{")
        for member_name, display, description, errata in members:
            out.extend(_comment(description, "///"))
            if errata:
                out.extend(_comment(f"errata: {errata}"))
            out.append(f"    {member_name} = {display},")
        out.append("};")

    out.append("")
    out.append("// Statically defined values (sentinel constants)")
    sentinels = doc.get("statically_defined_values", {}).get("ife_version", {})
    for _, entries in sorted(sentinels.items(), key=lambda kv: version_key(kv[0])):
        for name, entry in entries.items():
            out.extend(_comment(entry.get("description", ""), "///"))
            if entry.get("errata"):
                out.extend(_comment(f"errata: {entry['errata']}"))
            canonical = _canonical_type(entry["type"], types)
            if canonical == "f16":
                bits = parse_int(entry["value"])
                out.append(f"/// Wire value: {_value_display(entry['value'])} (IEEE binary16).")
                literal = _half_literal(bits)
            else:
                literal = _value_display(entry["value"])
            out.append(f"inline constexpr {_cpp_of(entry['type'], types)} {name} = {literal};")

    out += ["", "} // namespace constants", "} // namespace IFE", "", "#endif // IFE_Constants_hpp", ""]
    return "\n".join(out)


def _emit_size_offset(fields: tuple[FieldLayout, ...], indent: str = "    ") -> list[str]:
    """size{} and offset{} namespaces for a field list."""
    out = [f"{indent}namespace size {{"]
    for field in fields:
        out.extend(_comment(field.description, f"{indent}///"))
        out.append(f"{indent}    inline constexpr std::size_t {field.name} = {field.size};")
    out.append(f"{indent}}}")
    out.append(f"{indent}namespace offset {{")
    for field in fields:
        out.append(f"{indent}    inline constexpr std::size_t {field.name} = {field.offset};")
    out.append(f"{indent}}}")
    return out


# Appends to `out` in place rather than returning lines; several helpers below
# share that convention.
def _emit_version_markers(
    out: list[str], indent: str, total_name: str, sizes: tuple[tuple[str, int], ...]
) -> None:
    """Cumulative size per version, each closed by v1's boundary marker.

    The form is copied from src/IrisCodecExtension.hpp:445-449: the size
    constant, the "Version N.M ends here." line, a dashed rule, a blank line,
    then the newest-version alias. The last group gets one too — the newest
    version also ends somewhere, and that is exactly where an amendment
    appends.
    """
    for version, size in sizes:
        suffix = version.replace(".", "_")
        out.append(f"{indent}inline constexpr std::size_t {total_name}_v{suffix} = {size};")
        out.append(f"{indent}// Version {version} ends here.")
        out.append(f"{indent}// -----------------------------------------------------------------------")
        out.append("")
    newest = sizes[-1][0].replace(".", "_")
    out.append(f"{indent}inline constexpr std::size_t {total_name} = {total_name}_v{newest};")


def _emit_structure(
    out: list[str], namespace: str, comment: str, fields: tuple[FieldLayout, ...], total_name: str, total: int
) -> None:
    out.append(f"// ---- {comment} ----" if comment else f"// ---- {namespace} ----")
    out.append(f"namespace {namespace} {{")
    out.extend(_emit_size_offset(fields))
    out.append(f"    inline constexpr std::size_t {total_name} = {total};")
    out.append("}")


def emit_vtables_header(layout: LayoutResult, document: dict[str, Any]) -> str:
    """IFE_VTables.hpp — derived per-block offset/size vtables."""
    out: list[str] = [
        _banner(document),
        "#ifndef IFE_VTables_hpp",
        "#define IFE_VTables_hpp",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        '#include "IFE_Constants.hpp"',
        "",
        "namespace IFE {",
        "namespace vtables {",
    ]

    # Primitives carry no version markers: a primitive can never gain a field.
    # Appending to a prefix would shift the own-fields of every block deriving
    # from it, moving bytes that already shipped. A marker there would promise
    # an amendment point that cannot legally exist.
    for primitive in layout.primitives.values():
        inherits = f" (inherits {primitive.extends})" if primitive.extends else ""
        _emit_structure(
            out, primitive.name, f"{primitive.name} primitive{inherits}",
            primitive.fields, "total_size", primitive.size,
        )
        out.append("")

    recovery_enum = _pascal("recovery_codes")
    for name, block in layout.blocks.items():
        out.append("")
        out.append(f"// ---- {name} ----")
        out.extend(_comment(block.description))
        out.append(f"namespace {name} {{")
        out.append(f"    // primitive: {block.primitive}")
        out.append(
            f"    inline constexpr ::IFE::constants::{recovery_enum} recovery_tag"
            f" = ::IFE::constants::{recovery_enum}::{block.recovery_tag};"
        )
        out.extend(_emit_size_offset(block.header_fields))
        _emit_version_markers(out, "    ", "header_size", block.header_sizes)
        if block.from_sof is not None:
            out.append(
                f"    /// Fixed at byte 0; occupies the first {block.from_sof} B of the file."
            )
            out.append(f"    inline constexpr std::size_t from_sof = {block.from_sof};")
        if block.entry_fields:
            if block.entry_fields:
                out.append("")
                out.append(f"    // ---- {block.entry_name} (entry, {block.entry_size} B) ----")
                out.append("    namespace entry {")
                out.extend(_emit_size_offset(block.entry_fields, indent="        "))
                out.append("    }")
                out.append("")
                _emit_version_markers(out, "    ", "entry_size", block.entry_sizes)
        out.append("}")

    out += ["", "} // namespace vtables", "} // namespace IFE", "", "#endif // IFE_VTables_hpp", ""]
    return "\n".join(out)

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
# IFE_Blocks.hpp — typed handles over the wire
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
# IFE_Blocks.hpp / .cpp — typed handles over the wire
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ #
# The header declares; the source defines. Both are produced from the same
# list of Member records in the same order, so the two files scroll in
# parallel — the structure IrisCodecExtension.hpp/.cpp has by hand, here by
# construction rather than by discipline.

_RESERVED_ACCESSORS = frozenset({"type", "recovery", "header_size", "entry_size", "size"})


class Member(NamedTuple):
    """One member function, rendered as a declaration and as a definition.

    Splitting the signature into parts is what lets the source qualify it
    (`Status FILE_HEADER::validate() const noexcept`) from the same record the
    header prints unqualified. Nothing may render one without the other.
    """

    doc: tuple[str, ...]        # /// lines, declaration only
    attrs: str                  # [[nodiscard]] and the like, declaration only
    ret: str
    name: str
    params: str
    quals: str                  # "const noexcept"
    body: tuple[str, ...]       # definition lines, without the braces


def _declare(out: list[str], member: Member, indent: str = "    ") -> None:
    out.extend(f"{indent}{line}" for line in member.doc)
    attrs = f"{member.attrs} " if member.attrs else ""
    out.append(f"{indent}{attrs}{member.ret} {member.name}({member.params}) {member.quals};")


def _define(out: list[str], owner: str, member: Member) -> None:
    out.append("")
    out.append(f"{member.ret} {owner}::{member.name}({member.params}) {member.quals} {{")
    out.extend(member.body)
    out.append("}")


def _accessor(field_name: str) -> str:
    """Accessor name for a field: the field name, lower-cased.

    RECOVERY would collide with the static `recovery` tag constant, so names
    clashing with a struct-scope member take a `_field` suffix. Mechanical, so
    the name is predictable from the spec.
    """
    name = field_name.lower()
    return f"{name}_field" if name in _RESERVED_ACCESSORS else name


def _version_of(since: str) -> int:
    major, minor = version_key(since)
    return (major << 16) | minor


def _read_expression(field: FieldLayout, vtable: str, types: dict[str, Any]) -> tuple[str, str]:
    """(return type, expression) for reading one field through IFE_Bytes."""
    at = f"__base + __offset + ::IFE::vtables::{vtable}::offset::{field.name}"
    if field.kind == "enum":
        enum = f"::IFE::constants::{_pascal(field.type_name)}"
        underlying = _cpp_of(field.type_name, types) if field.type_name in types else field.cpp_type
        return enum, f"static_cast<{enum}>(::IFE::load<{underlying}>({at}))"
    canonical = _canonical_type(field.type_name, types)
    if canonical == "u24":
        return "std::uint32_t", f"::IFE::load_u24({at})"
    if canonical == "u40":
        return "std::uint64_t", f"::IFE::load_u40({at})"
    if canonical == "f16":
        return "float", f"::IFE::load_f16({at})"
    return field.cpp_type, f"::IFE::load<{field.cpp_type}>({at})"


def _field_members(
    fields: tuple[FieldLayout, ...],
    vtable: str,
    types: dict[str, Any],
    stride_gated: bool = False,
) -> list[Member]:
    """One Member per readable field, in wire order."""
    members: list[Member] = []
    for field in fields:
        if field.kind == "constant":
            continue  # always holds its sentinel; validated, never read
        doc = tuple(f"/// {line}" for line in field.description.splitlines() if line.strip())

        if field.points_to:
            target = field.points_to
            note = (
                "Empty when the offset is NULL_OFFSET."
                if field.nullable
                else "Required: never NULL_OFFSET in a valid file."
            )
            body = [
                f"    const ::IFE::Offset __at = ::IFE::load<::IFE::Offset>(",
                f"        __base + __offset + ::IFE::vtables::{vtable}::offset::{field.name});",
            ]
            if field.nullable:
                body.append(f"    if (__at == ::IFE::constants::NULL_OFFSET) return {target}{{}};")
            body.append(f"    return {target}{{__base, __at, __size, __version}};")
            members.append(Member(
                doc=doc + (f"/// Handle to the {target} block this offset references. {note}",),
                attrs="[[nodiscard]]", ret=target, name=_accessor(field.name),
                params="", quals="const noexcept", body=tuple(body),
            ))
            continue

        cpp, expression = _read_expression(field, vtable, types)
        if field.since != "1.0":
            guard = f"__version < {_version_of(field.since):#010x}u"
            if stride_gated:
                guard += (
                    f"\n        || __stride < ::IFE::vtables::{vtable}::offset::{field.name}"
                    f" + ::IFE::vtables::{vtable}::size::{field.name}"
                )
            members.append(Member(
                doc=doc + (f"/// Added in {field.since}; empty when the file predates it.",),
                attrs="[[nodiscard]]", ret=f"std::optional<{cpp}>", name=_accessor(field.name),
                params="", quals="const noexcept",
                body=(f"    if ({guard}) return std::nullopt;", f"    return {expression};"),
            ))
        else:
            members.append(Member(
                doc=doc, attrs="[[nodiscard]]", ret=cpp, name=_accessor(field.name),
                params="", quals="const noexcept", body=(f"    return {expression};",),
            ))
    return members


def _version_boundaries(fields: tuple[FieldLayout, ...]) -> dict[int, str]:
    """Index -> version whose last readable field sits there."""
    marks: dict[int, str] = {}
    readable = [f for f in fields if f.kind != "constant"]
    for i, field in enumerate(readable):
        if i + 1 == len(readable) or readable[i + 1].since != field.since:
            marks[i] = field.since
    return marks


def _validate_member(name: str, block: Any, layout: LayoutResult) -> Member:
    """The block's own structural checks, in the order v1 performs them.

    Reproduces DATA_BLOCK::validate_offset (IrisCodecExtension.cpp:778-803) and
    the array bounds check from LAYER_EXTENTS::validate_full (:1641-1686).
    Deliberately absent is anything semantic: FILE_SIZE agreeing with the size
    the OS reports is a fact about the file, not the layout, and belongs to the
    runtime.
    """
    primitive = layout.primitives[block.primitive]
    vt = f"::IFE::vtables::{name}"
    body: list[str] = [
        "    if (!*this)",
        '        return {Check::NOT_CONSTRUCTED, type, "", __offset, __size, __offset};',
    ]
    by_name = {f.name: f for f in primitive.fields}
    if "VALIDATION" in by_name:
        body += [
            "    // A block stores its own offset, so a pointer that landed here can",
            "    // prove it landed where it meant to.",
            "    if (const ::IFE::Offset __v = validation(); __v != __offset)",
            '        return {Check::BAD_VALIDATION, type, "VALIDATION", __v, __offset, __offset};',
        ]
    for field in primitive.fields:
        if field.kind == "constant":
            body += [
                f"    if (const auto __c = ::IFE::load<{field.cpp_type}>(",
                f"            __base + __offset + {vt}::offset::{field.name});",
                f"        __c != ::IFE::constants::{field.constant})",
                f'        return {{Check::BAD_CONSTANT, type, "{field.name}", __c,',
                f"                ::IFE::constants::{field.constant}, __offset}};",
            ]
    body += [
        "    if (const auto __r = recovery_field(); __r != recovery)",
        '        return {Check::BAD_RECOVERY, type, "RECOVERY",',
        "                static_cast<std::uint64_t>(__r),",
        "                static_cast<std::uint64_t>(recovery), __offset};",
    ]
    if block.primitive in ("array", "byte_array"):
        if block.entry_fields:
            floor = block.entry_sizes[0][1] if block.entry_sizes else block.entry_size
            body += [
                "",
                "    // The stride the encoder wrote must at least hold the entry this",
                "    // build knows; a wider one is a later version and is fine.",
                f"    if (const std::uint16_t __st = stride(); __st < {floor})",
                f'        return {{Check::BAD_STRIDE, type, "STRIDE", __st, {floor}, __offset}};',
            ]
            span = "static_cast<std::uint64_t>(stride()) * count()"
        else:
            body += ["", "    // A byte array stores no stride; its stride is one by definition."]
            span = "static_cast<std::uint64_t>(count())"
        body += [
            "",
            "    // Expressed as a subtraction so the multiplication cannot wrap:",
            "    // u16 * u32 fits a u64 comfortably.",
            "    const ::IFE::Offset __begin = entries_begin();",
            f"    const std::uint64_t __span = {span};",
            "    if (__begin > __size || __span > __size - __begin)",
            '        return {Check::ARRAY_OVERRUN, type, "COUNT", __span,',
            "                __size - (__begin > __size ? __size : __begin), __offset};",
        ]
    body.append("    return {};")
    return Member(
        doc=("/// Structural checks on this block alone. Never allocates or throws.",),
        attrs="[[nodiscard]]", ret="Status", name="validate", params="",
        quals="const noexcept", body=tuple(body),
    )


def _validate_deep_member(name: str, block: Any) -> Member:
    """Recurse the offset graph. Successor to v1's hand-threaded validate_full.

    v1 chained each block's check into its children by hand (:869-900), which
    is why a block added later is easy to forget. Here the walk is derived from
    `points_to`, so every edge in the schema is followed by construction —
    including edges leaving array *entries*, which a header-only walk would
    skip and which is exactly where IMAGE_BYTES and ANNOTATION_BYTES hang.
    """
    body: list[str] = [
        "    if (const Status __s = validate(); !__s) return __s;",
        "    if (__path.contains(__offset))",
        '        return {Check::CYCLE, type, "", __offset, 0, __offset};',
        "    if (!__path.push(__offset))",
        '        return {Check::CYCLE, type, "", __path.depth, MAX_BLOCK_DEPTH, __offset};',
    ]

    def walk(field, source: str, indent: str) -> list[str]:
        handle = f"__t_{field.name.lower()}"
        lines = [f"{indent}{{", f"{indent}    const auto {handle} = {source};"]
        if field.nullable:
            lines += [
                f"{indent}    // Optional: NULL_OFFSET means absent and is legal; any",
                f"{indent}    // other unusable value is not.",
                f"{indent}    if ({handle}.__offset != ::IFE::constants::NULL_OFFSET) {{",
            ]
        else:
            lines.append(f"{indent}    {{")
        inner = indent + "        "
        lines += [
            f"{inner}if (!{handle})",
            f'{inner}    return {{Check::OUT_OF_BOUNDS, type, "{field.name}",',
            f"{inner}            {handle}.__offset, __size, __offset}};",
            f"{inner}if (const Status __s = {handle}.validate_deep(__path); !__s) return __s;",
            f"{indent}    }}",
            f"{indent}}}",
        ]
        return lines

    for field in (f for f in block.header_fields if f.points_to):
        body += walk(field, f"{_accessor(field.name)}()", "    ")
    entry_edges = [f for f in block.entry_fields if f.points_to]
    if entry_edges:
        body += ["", "    // Edges that leave from entries, one per entry.",
                 "    for (std::uint32_t __i = 0; __i < count(); ++__i) {",
                 "        const auto __e = entry(__i);"]
        for field in entry_edges:
            body += walk(field, f"__e.{_accessor(field.name)}()", "        ")
        body.append("    }")
    body += ["    __path.pop();", "    return {};"]
    return Member(
        doc=("/// validate(), then every block this one reaches, transitively.",),
        attrs="[[nodiscard]]", ret="Status", name="validate_deep",
        params="VisitPath& __path", quals="const noexcept", body=tuple(body),
    )


_STATUS_PREAMBLE = """
// ---- validation vocabulary ----
// Generated validators never allocate, never throw and never format a string.
// They report a code plus the operands v1 interpolated into its messages
// (IrisCodecExtension.cpp:784-800) and leave the wording to the runtime, which
// has the JSON descriptions and is not on the hot path.

enum class Check : std::uint8_t {
    OK = 0,
    NOT_CONSTRUCTED,   ///< no base pointer, null offset, or header past EOF
    OUT_OF_BOUNDS,     ///< an offset field points outside the file
    BAD_VALIDATION,    ///< VALIDATION does not equal the block's own offset
    BAD_RECOVERY,      ///< RECOVERY is not this block's tag
    BAD_CONSTANT,      ///< a constant field does not hold its sentinel
    BAD_STRIDE,        ///< STRIDE is zero, or narrower than the entry it must hold
    ARRAY_OVERRUN,     ///< the entry run extends past the end of the file
    VERSION_TOO_NEW,   ///< reserved for the runtime; see below
    CYCLE,             ///< an offset chain returns to a block already on the path
};

/// Everything needed to describe a failure, unformatted.
struct Status {
    Check         code     = Check::OK;
    const char*   block    = "";
    const char*   field    = "";
    std::uint64_t found    = 0;
    std::uint64_t expected = 0;
    ::IFE::Offset at       = 0;

    constexpr explicit operator bool() const noexcept { return code == Check::OK; }
};

/// A newer file is never a structural failure: append-only guarantees its 1.0
/// prefix is readable, so VERSION_TOO_NEW is never returned by a generated
/// validator. It exists for the runtime to raise as a warning, matching v1
/// (IrisCodecExtension.cpp:853-865), which warns and continues.

inline constexpr std::size_t MAX_BLOCK_DEPTH = 16;

/// The chain of offsets from the root to the block being checked.
///
/// Cycle detection needs the *ancestry*, not every block ever seen: a file may
/// hold thousands of annotations each with its own byte array, all legitimate
/// separate visits, and a global set would reject the second of two entries
/// pointing at one target. A cycle is an offset that reappears on the current
/// path, bounded by the block graph's depth.
struct VisitPath {
    ::IFE::Offset entries[MAX_BLOCK_DEPTH]{};
    std::size_t   depth = 0;

    [[nodiscard]] constexpr bool contains(::IFE::Offset __o) const noexcept {
        for (std::size_t __i = 0; __i < depth; ++__i)
            if (entries[__i] == __o) return true;
        return false;
    }
    [[nodiscard]] constexpr bool push(::IFE::Offset __o) noexcept {
        if (depth == MAX_BLOCK_DEPTH) return false;
        entries[depth++] = __o;
        return true;
    }
    constexpr void pop() noexcept { if (depth) --depth; }
};
"""


def _block_members(
    name: str, block: Any, layout: LayoutResult, types: dict[str, Any]
) -> list[Member]:
    """Every member of one block struct, declaration order == definition order."""
    primitive = layout.primitives[block.primitive]
    own = tuple(f for f in block.header_fields if f not in primitive.fields)
    members = _field_members(own, name, types)
    members.append(_validate_member(name, block, layout))
    members.append(_validate_deep_member(name, block))
    return members


def _entry_members(name: str, block: Any, types: dict[str, Any]) -> list[Member]:
    return _field_members(block.entry_fields, f"{name}::entry", types, stride_gated=True)


def _emit_primitive_bases(out: list[str], layout: LayoutResult, types: dict[str, Any]) -> None:
    """The schema's primitive hierarchy, as plain structs.

    Not templates: v1 keeps DATA_BLOCK a plain base by passing the per-type
    data down as arguments (IrisCodecExtension.hpp:405 —
    validate_offset(__base, type, recovery)) rather than encoding it in the
    type. The same trick applies to the bounds check, so `fits` takes the
    derived block's header_size instead of the base having to know it. Plain
    bases are what let every body live in the .cpp.
    """
    for primitive in layout.primitives.values():
        base = f" : public {primitive.extends}" if primitive.extends else ""
        out.append("")
        out.extend(_comment(primitive.description))
        out.append(f"struct {primitive.name}{base} {{")
        if primitive.extends is None:
            out += [
                "    const ::IFE::BYTE* __base    = nullptr;",
                "    ::IFE::Offset      __offset  = ::IFE::constants::NULL_OFFSET;",
                "    ::IFE::Size        __size    = 0;   ///< total file size",
                "    std::uint32_t      __version = 0;   ///< major<<16 | minor, from FILE_HEADER",
                "",
                "    /// Whether a block of `__header_size` bytes fits here. Stricter than",
                "    /// v1's operator bool (IrisCodecExtension.cpp:774-777), which checks",
                "    /// only that the offset is in range: requiring the whole header to fit",
                "    /// makes a truncated file fail at construction rather than mid-read.",
                "    [[nodiscard]] constexpr bool fits(::IFE::Size __header_size) const noexcept {",
                "        return __base != nullptr",
                "            && __offset != ::IFE::constants::NULL_OFFSET",
                "            && __offset + __header_size <= __size;",
                "    }",
            ]
        inherited = layout.primitives[primitive.extends].fields if primitive.extends else ()
        introduced = tuple(f for f in primitive.fields if f not in inherited)
        for member in _field_members(introduced, primitive.name, types):
            out.append("")
            _declare(out, member)
        if primitive.name in ("array", "byte_array"):
            out += [
                "",
                "    /// Where the entry run starts. Takes the derived block's header size",
                "    /// for the same reason `fits` does.",
                "    [[nodiscard]] constexpr ::IFE::Offset entries_at(",
                "            ::IFE::Size __header_size) const noexcept {",
                "        return __offset + __header_size;",
                "    }",
            ]
        out.append("};")


def emit_blocks_header(
    layout: LayoutResult, types: dict[str, Any], header: dict[str, Any]
) -> str:
    """IFE_Blocks.hpp — declarations only, readable as an outline of the format."""
    out: list[str] = [
        _banner(header),
        "#ifndef IFE_Blocks_hpp",
        "#define IFE_Blocks_hpp",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <optional>",
        "",
        '#include "IFE_Constants.hpp"',
        '#include "IFE_VTables.hpp"',
        '#include "IFE_Bytes.hpp"',
        "",
        "// Definitions live in IFE_Blocks.cpp, which follows this file section for",
        "// section. Define IFE_HEADER_ONLY before including this header to fold them",
        "// in at the bottom and use the generated layer without linking anything.",
        "",
        "namespace IFE {",
        "namespace blocks {",
        "",
        "// Forward declarations: offset fields return handles to other blocks, and",
        "// the reference graph has cycles no ordering would resolve.",
    ]
    for name in layout.blocks:
        out.append(f"struct {name};")

    out.append("")
    out.extend(_STATUS_PREAMBLE.strip("\n").splitlines())

    out.append("")
    out.append("// ---- primitive block types ----")
    out.append("// The hierarchy the schema declares, as real base classes.")
    _emit_primitive_bases(out, layout, types)

    for name, block in layout.blocks.items():
        primitive = layout.primitives[block.primitive]
        out.append("")
        out.append(f"// ---- {name} ----")
        out.extend(_comment(block.description))
        out.append(f"struct {name} : public {block.primitive} {{")
        out.append(f'    static constexpr char type[] = "{name}";')
        recovery_enum = _pascal("recovery_codes")
        out.append(f"    static constexpr ::IFE::constants::{recovery_enum} recovery =")
        out.append(f"        ::IFE::constants::{recovery_enum}::{block.recovery_tag};")
        out.append(
            f"    static constexpr ::IFE::Size header_size = ::IFE::vtables::{name}::header_size;"
        )
        out.append("")
        out.append("    constexpr explicit operator bool() const noexcept { return fits(header_size); }")

        if block.entry_fields:
            entry = block.entry_name or f"{name}_ENTRY"
            out.append("")
            out.append(f"    /// One {entry}, addressed by the array's stored stride.")
            out.append(f"    struct {entry} {{")
            out += [
                "        const ::IFE::BYTE* __base    = nullptr;",
                "        ::IFE::Offset      __offset  = 0;",
                "        ::IFE::Size        __size    = 0;   ///< total file size",
                "        std::uint16_t      __stride  = 0;   ///< as written, not as compiled",
                "        std::uint32_t      __version = 0;",
            ]
            marks = _version_boundaries(block.entry_fields)
            for index, member in enumerate(_entry_members(name, block, types)):
                out.append("")
                _declare(out, member, indent="        ")
                if index in marks:
                    out.append(f"        // Version {marks[index]} ends here.")
                    out.append("        // -------------------------------------------------------")
            out.append("    };")
            out.append("")
            out.append("    /// Entry `i`, stepped by the STRIDE the encoder wrote — never by the")
            out.append("    /// size this build was compiled with.")
            out.append(f"    [[nodiscard]] {entry} entry(std::uint32_t __i) const noexcept;")
            out.append("    [[nodiscard]] ::IFE::Offset entries_begin() const noexcept;")
        elif block.primitive == "byte_array":
            out.append("")
            out.append("    /// The whole byte run. Its interpretation is not this layer's")
            out.append("    /// business: slicing comes from a sizes array elsewhere and the")
            out.append("    /// character encoding is normative prose.")
            out.append("    [[nodiscard]] ::IFE::ByteSpan bytes() const noexcept;")
            out.append("    [[nodiscard]] ::IFE::Offset entries_begin() const noexcept;")

        own = tuple(f for f in block.header_fields if f not in primitive.fields)
        marks = _version_boundaries(own)
        for index, member in enumerate(_block_members(name, block, layout, types)):
            out.append("")
            _declare(out, member)
            if index in marks:
                out.append(f"    // Version {marks[index]} ends here.")
                out.append("    // ---------------------------------------------------------------")
        out.append("")
        out.append("    /// Convenience: deep validation from a fresh path.")
        out.append("    [[nodiscard]] Status validate_deep() const noexcept;")
        out.append("};")

    out += [
        "",
        "}  // namespace blocks",
        "}  // namespace IFE",
        "",
        "#ifdef IFE_HEADER_ONLY",
        "// Header-only mode: fold the definitions in. The include is a no-op on the",
        "// way back through this file's guard, so the recursion terminates.",
        '#include "IFE_Blocks.cpp"',
        "#endif",
        "",
        "#endif  // IFE_Blocks_hpp",
        "",
    ]
    return "\n".join(out)


def emit_blocks_source(
    layout: LayoutResult, types: dict[str, Any], header: dict[str, Any]
) -> str:
    """IFE_Blocks.cpp — definitions, in the header's order, section for section."""
    out: list[str] = [
        _banner(header),
        "#ifndef IFE_Blocks_cpp",
        "#define IFE_Blocks_cpp",
        "",
        "// Compiled as its own translation unit by default; included from",
        "// IFE_Blocks.hpp when IFE_HEADER_ONLY is defined, in which case every",
        "// definition needs internal-or-inline linkage so more than one TU may",
        "// include it. IFE_BLOCKS_INLINE is what makes both work.",
        '#include "IFE_Blocks.hpp"',
        "",
        "#ifdef IFE_HEADER_ONLY",
        "#  define IFE_BLOCKS_INLINE inline",
        "#else",
        "#  define IFE_BLOCKS_INLINE",
        "#endif",
        "",
        "namespace IFE {",
        "namespace blocks {",
    ]

    for primitive in layout.primitives.values():
        inherited = layout.primitives[primitive.extends].fields if primitive.extends else ()
        introduced = tuple(f for f in primitive.fields if f not in inherited)
        members = _field_members(introduced, primitive.name, types)
        if not members:
            continue
        out.append("")
        out.append(f"// ---- {primitive.name} (primitive) ----")
        for member in members:
            out.append("")
            out.append(
                f"IFE_BLOCKS_INLINE {member.ret} {primitive.name}::{member.name}"
                f"({member.params}) {member.quals} {{"
            )
            out.extend(member.body)
            out.append("}")

    for name, block in layout.blocks.items():
        out.append("")
        out.append(f"// ---- {name} ----")

        if block.entry_fields:
            entry = block.entry_name or f"{name}_ENTRY"
            for member in _entry_members(name, block, types):
                out.append("")
                out.append(
                    f"IFE_BLOCKS_INLINE {member.ret} {name}::{entry}::{member.name}"
                    f"({member.params}) {member.quals} {{"
                )
                out.extend(member.body)
                out.append("}")
            out.append("")
            out.append(f"IFE_BLOCKS_INLINE ::IFE::Offset {name}::entries_begin() const noexcept {{")
            out.append("    return entries_at(header_size);")
            out.append("}")
            out.append("")
            out.append(
                f"IFE_BLOCKS_INLINE {name}::{entry} {name}::entry(std::uint32_t __i) const noexcept {{"
            )
            out.append(f"    return {entry}{{__base,")
            out.append("                 entries_begin() + static_cast<::IFE::Offset>(__i) * stride(),")
            out.append("                 __size, stride(), __version};")
            out.append("}")
        elif block.primitive == "byte_array":
            out.append("")
            out.append(f"IFE_BLOCKS_INLINE ::IFE::Offset {name}::entries_begin() const noexcept {{")
            out.append("    return entries_at(header_size);")
            out.append("}")
            out.append("")
            out.append(f"IFE_BLOCKS_INLINE ::IFE::ByteSpan {name}::bytes() const noexcept {{")
            out.append("    return {__base + entries_begin(), count()};")
            out.append("}")

        for member in _block_members(name, block, layout, types):
            out.append("")
            out.append(
                f"IFE_BLOCKS_INLINE {member.ret} {name}::{member.name}"
                f"({member.params}) {member.quals} {{"
            )
            out.extend(member.body)
            out.append("}")

        out.append("")
        out.append(f"IFE_BLOCKS_INLINE Status {name}::validate_deep() const noexcept {{")
        out.append("    VisitPath __path;")
        out.append("    return validate_deep(__path);")
        out.append("}")

    out += [
        "",
        "}  // namespace blocks",
        "}  // namespace IFE",
        "",
        "#endif  // IFE_Blocks_cpp",
        "",
    ]
    return "\n".join(out)
