"""AsciiDoc emission for the IFE specification document.

One file per item, not one file per document. The narrative
(``spec/ife_spec.adoc``) pulls each in with Asciidoctor's native ``include::``,
so a section moves without dragging unrelated tables along and the document
never contains a hand-written offset. This is how Khronos assembles the Vulkan
specification from ``vk.xml``, and the reason no bespoke anchor syntax or
preprocessor exists here.

Emitted into ``generated_docs/``:

    layout/<BLOCK>.adoc          one block's header table
    layout/<BLOCK>_entry.adoc    that block's entry table, where it has one
    layout/primitive_<NAME>.adoc a shared prefix (file_header, block, array…)
    constants/<GROUP>.adoc       one enumeration, or the sentinel values
    provenance.adoc              schema and generator version of this build

Every table is a two-column-plus AsciiDoc table with a title, so the published
document gets numbered captions and cross-references for free.
"""
from __future__ import annotations

from typing import Any

from ..model.layout import BlockLayout, FieldLayout, LayoutResult, constants_groups, is_banner, is_enum_group, parse_int, version_key

# Emitted paths are relative to the docs root; the narrative includes them by
# these names, so they are part of the contract with spec/ife_spec.adoc.
LAYOUT_DIR = "layout"
CONSTANTS_DIR = "constants"


def _banner(witness_hash: str) -> list[str]:
    return [
        "////",
        "Generated by `python3 -m generator` from spec/*.json — DO NOT EDIT BY HAND.",
        "Offsets and sizes are derived from field order and width, never stored.",
        f"Wire witness: sha256 {witness_hash} — --check verifies this file matches the current spec.",
        "////",
        "",
    ]


def section_anchor(block_name: str) -> str:
    """`TILE_TABLE` -> `ife-tile-table`, the anchor its section declares."""
    return "ife-" + block_name.lower().replace("_", "-")


def _type_column(field: FieldLayout) -> str:
    if field.points_to:
        # A cross-reference, so the reader can follow the offset to the block
        # it addresses instead of hunting for it in the contents.
        return f"`{field.type_name}` -> <<{section_anchor(field.points_to)}>>"
    if field.kind == "enum":
        return f"enum `{field.type_name}`"
    if field.kind == "constant":
        return f"`{field.type_name}` = `{field.constant}`"
    return f"`{field.type_name}`"


def _cell(text: str) -> str:
    """A table cell: strip the newlines AsciiDoc would treat as a row break."""
    return " ".join(text.split()).replace("|", "\\|")


def _layout_table(title: str, fields: tuple[FieldLayout, ...]) -> list[str]:
    # A trailer's fields sit behind the anchor, so its column is a displacement
    # rather than an offset and the heading has to say which -- "Offset -5" in
    # a table whose other rows count forward would read as an erratum.
    backward = any(field.offset < 0 for field in fields)
    out = [
        f".{title}",
        '[cols="2,2,1,1,1,5",options="header",frame=all,grid=all]',
        "|===",
        f"|Field |Type |{'Displacement' if backward else 'Offset'} |Size |Optional |Description",
        "",
    ]
    for field in fields:
        # Optional == the spec's `nullable: true` — the offset may hold
        # NULL_OFFSET. Fields without the key are required.
        out.append(
            f"|`{field.name}` |{_type_column(field)} |{field.offset} |{field.size} "
            f"|{'Yes' if field.nullable else 'No'} |{_cell(field.description)}"
        )
    out += ["|===", ""]
    return out


def emit_block_layout(block: BlockLayout, witness_hash: str) -> str:
    """One block's header table, as its own includable file."""
    out = _banner(witness_hash)
    out += _layout_table(
        f"`{block.name}` header — {block.header_size} bytes"
        + (", ending where the stream it precedes begins" if block.backward else "")
        + (f", at byte 0 ({block.from_sof} B from start of file)" if block.from_sof is not None else "")
        + (f", recovery tag `{block.recovery_tag}` (0x{block.recovery_value:04X})"
           if block.recovery_tag else ", no recovery tag"),
        block.header_fields,
    )
    return "\n".join(out)


def emit_entry_layout(block: BlockLayout, witness_hash: str) -> str:
    """One array block's entry table."""
    out = _banner(witness_hash)
    out += _layout_table(
        f"`{block.entry_name}` entry — {block.entry_size} bytes, "
        f"addressed by the array's stored `STRIDE`",
        block.entry_fields,
    )
    return "\n".join(out)


def emit_primitive_layout(primitive: Any, witness_hash: str) -> str:
    """A shared prefix every derived block carries."""
    out = _banner(witness_hash)
    inherits = f", extending `{primitive.extends}`" if primitive.extends else ""
    where = " before the anchor" if getattr(primitive, "backward", False) else ""
    out += _layout_table(
        f"`{primitive.name}` primitive — {primitive.size} bytes{where}{inherits}",
        primitive.fields,
    )
    return "\n".join(out)


def emit_constants_table(
    group_name: str, group: dict[str, Any], recovery_prefix: int, witness_hash: str
) -> str:
    """One enumeration, or the statically defined values."""
    out = _banner(witness_hash)
    title = f"`{group_name}`"
    if is_enum_group(group):
        title += f" — `{group['underlying_type']}`"

    out += [
        f".{title}",
        '[cols="2,1,5",options="header",frame=all,grid=all]',
        "|===",
        "|Name |Value |Description",
        "",
    ]
    derived = group_name == "recovery_codes"
    index = 0
    for _, entries in sorted(group.get("ife_version", {}).items(), key=lambda kv: version_key(kv[0])):
        for name, raw in entries.items():
            entry = raw if isinstance(raw, dict) else {"value": raw}
            value = entry.get("value")
            if derived:
                # Tag values are derived from position, as the generator
                # assigns them; the document must show what is on the wire.
                display = f"0x{recovery_prefix + parse_int(value):04X}"
            elif isinstance(value, str) and value.lower().startswith("0x"):
                display = value
            elif value is None:
                display = ""
            else:
                display = str(parse_int(value))
            out.append(
                f"|`{name}` |{display} |{_cell(str(entry.get('description', '')))}"
            )
            index += 1
    out += ["|===", ""]
    return "\n".join(out)


_MONTHS = ("January", "February", "March", "April", "May", "June",
           "July", "August", "September", "October", "November", "December")


def _readable_date(iso: str) -> str:
    """`2025-05` -> `May 2025`; `2025-05-14` -> `14 May 2025`.

    Month precision is allowed on purpose: a specification is usually ratified
    in a month people remember, and inventing a day to satisfy a format would
    be stating something nobody verified.
    """
    parts = iso.split("-")
    if len(parts) < 2:
        return iso
    month = _MONTHS[int(parts[1]) - 1]
    if len(parts) == 2:
        return f"{month} {parts[0]}"
    return f"{int(parts[2])} {month} {parts[0]}"


def emit_revision_history(document: dict[str, Any], witness_hash: str) -> str:
    """The document's revision history, as a labelled list.

    Deliberately not a table. One column holds a paragraph of prose and the
    others hold a few characters each, which is exactly the shape a table
    handles worst -- the summary wraps into a narrow column while Version and
    Date sit in a sea of whitespace. A labelled list gives the version the role
    a table gives a row key, and lets the summary run as a paragraph.

    The label is the version itself rather than an ordinal: `1.0` is what a
    reader looks up, and an auto-numbered `1.` beside it would be a second,
    meaningless numbering.

    Rendered from ife_header.json, so the version the document claims and the
    version its history records are one fact. Oldest first.
    """
    out = _banner(witness_hash)
    for entry in document.get("revisions", []):
        version = entry.get("version", "?")
        authors = ", ".join(entry.get("authors", [])) or "author not recorded"
        date = entry.get("date")
        status = entry.get("status", "unreleased")
        when = f"{status} {_readable_date(date)}" if date else status
        out += [
            f"*Version {version}* — {when}, {authors}::",
            _cell(entry.get("summary", "")),
        ]
        # A revision may carry an erratum: something the version did that its
        # summary should not have to bury, because a reader looking for it is
        # looking for exactly this. Rendered as an admonition inside the list
        # item, which is what the `+` continuation is for.
        if errata := entry.get("errata"):
            out += ["+", "[CAUTION]", "====", _cell(errata), "===="]
        out.append("")
    return "\n".join(out)


def emit_attributes(document: dict[str, Any], generator_version: str) -> str:
    """The document header attributes, from the specification's identity.

    Asciidoctor builds the title page out of document attributes rather than
    body content, so the cover's version, date, authors and licence cannot be
    an `include::` of a rendered block -- they have to *be* attributes. This
    emits them, which keeps the cover page sourced from ife_header.json like
    everything else rather than hand-copied into the narrative.

    The newest revision is the one the cover states: it is the version this
    document *is*.
    """
    version = document.get("version", {})
    label = f"{version.get('major', 0)}.{version.get('minor', 0)}"
    revisions = document.get("revisions", [])
    current = next((r for r in revisions if r.get("version") == label), None) or {}
    authors = current.get("authors", [])

    out = [
        "// Generated from spec/ife_header.json -- DO NOT EDIT BY HAND.",
        "// No blank line or block comment below: either would end the document",
        "// header, and the title page is built from header attributes alone.",
        f":revnumber: {label}",
        f":revdate: {_readable_date(current['date']) if current.get('date') else current.get('status', 'unreleased')}",
        # The default title page has slots for title, subtitle, authors and the
        # revision line only -- no copyright field. The remark is the one part
        # of the revision line that takes free text, so the legal terms ride
        # there rather than being hand-typed onto the cover and going stale.
        # One line, deliberately: an attribute value cannot span lines, and the
        # continuation would land inside the document header where it is read
        # as content rather than as part of the value.
        ":revremark: " + " · ".join(
            x for x in (current.get("status"), document.get("copyright"), document.get("license")) if x
        ),
        # `author` drives the title page's byline; the published document words
        # it "Prepared by", which asciidoctor-pdf renders from the same field.
        # `author`, joined: the parser derives `authors` itself and does not
        # take it as an input, so setting that one renders nothing.
        f":author: {', '.join(authors)}" if authors else "",
        f":copyright: {document.get('copyright', '')}",
        f":license: {document.get('license', '')}",
        f":generator-version: {generator_version}",
        f":repository: {document.get('repository', '')}",
    ]
    return "\n".join(out)


def emit_provenance(document: dict[str, Any], generator_version: str, witness_hash: str) -> str:
    """What produced this document.

    A ratified specification that cannot be reproduced years later is not
    reproducible in any useful sense, and the generator is part of the standard
    now — not merely a build tool. So the published document states both the
    schema version and the generator that rendered it.
    """
    version = document.get("version", {})
    return "\n".join(
        _banner(witness_hash)
        + [
            "[cols=\"1,3\",frame=none,grid=rows]",
            "|===",
            f"|Specification version |{version.get('major', 0)}.{version.get('minor', 0)}",
            f"|Status |{document.get('status', 'draft')}",
            f"|Generator |{generator_version}",
            f"|Copyright |{document.get('copyright', '')}",
            f"|Licence |{document.get('license', '')}",
            "|===",
            "",
        ]
    )


def emit_documents(
    layout: LayoutResult, constants_doc: dict[str, Any], document: dict[str, Any],
    generator_version: str, recovery_prefix: int, witness_hash: str,
) -> dict[str, str]:
    """Every generated AsciiDoc file: relative path -> content."""
    out: dict[str, str] = {
        "provenance.adoc": emit_provenance(document, generator_version, witness_hash),
        "revision_history.adoc": emit_revision_history(document, witness_hash),
        "attributes.adoc": emit_attributes(document, generator_version),
    }

    for primitive in layout.primitives.values():
        out[f"{LAYOUT_DIR}/primitive_{primitive.name}.adoc"] = emit_primitive_layout(
            primitive, witness_hash
        )

    for name, block in layout.blocks.items():
        out[f"{LAYOUT_DIR}/{name}.adoc"] = emit_block_layout(block, witness_hash)
        if block.entry_fields:
            out[f"{LAYOUT_DIR}/{name}_entry.adoc"] = emit_entry_layout(block, witness_hash)

    for group_name, group in constants_groups(constants_doc).items():
        out[f"{CONSTANTS_DIR}/{group_name}.adoc"] = emit_constants_table(
            group_name, group, recovery_prefix, witness_hash
        )
    return out
