"""Markdown emission for the IFE code generator.

First cut of the doc emitter: derived layout tables only. These are the
tables the spec document interleaves at the ``{{layout:BLOCK}}`` /
``{{entry_layout:BLOCK}}`` anchors (Phase 5 assembles the full document).
"""
from __future__ import annotations

from ..model.layout import BlockLayout, FieldLayout, LayoutResult


def _type_column(field: FieldLayout) -> str:
    if field.kind == "enum":
        return f"enum `{field.type_name}`"
    if field.kind == "constant":
        return f"`{field.type_name}` = `{field.constant}`"
    return f"`{field.type_name}`"


def _escape(text: str) -> str:
    """Escape pipe characters for markdown table cells."""
    return text.replace("|", "\\|")


def _layout_table(out: list[str], title: str, fields: tuple[FieldLayout, ...]) -> None:
    out.append(f"### {title}")
    out.append("")
    out.append("| Field | Type | Offset | Size | Description |")
    out.append("|---|---|---|---|---|")
    for field in fields:
        out.append(
            f"| `{field.name}` | {_type_column(field)} | {field.offset} | {field.size} | {_escape(field.description)} |"
        )
    out.append("")


def _block_section(out: list[str], block: BlockLayout) -> None:
    from_sof = f"; {block.from_sof} B from SOF" if block.from_sof is not None else ""
    if block.kind == "array":
        entry = f"; entry `{block.entry_name}` {block.entry_size} B" if block.entry_fields else "; byte-blob entry (stride 1)"
        heading = f"## `{block.name}` — array block ({block.header_size} B{from_sof}{entry})"
    else:
        heading = f"## `{block.name}` — header block ({block.header_size} B{from_sof})"
    out.append(heading)
    out.append("")
    out.append(f"Recovery tag: `{block.recovery_tag}` (`0x{block.recovery_value:04X}`)")
    out.append("")
    if block.description:
        out.append(f"{block.description}")
        out.append("")
    _layout_table(out, "Header fields", block.header_fields)
    if block.entry_fields:
        _layout_table(out, f"Entry `{block.entry_name}` ({block.entry_size} B)", block.entry_fields)


def emit_layout_markdown(layout: LayoutResult) -> str:
    """layout_tables.md — derived offsets/sizes for every structure."""
    out: list[str] = [
        "# IFE derived layout tables (generated — DO NOT EDIT)",
        "",
        "Generated by `python3 -m generator` from `spec/ife_fields.json` and",
        "`spec/ife_constants.json`. Offsets and sizes are derived, never stored.",
        "",
        "## `file_preamble` ({layout.preamble_size} B)".format(layout=layout),
        "",
        "| Field | Type | Offset | Size | Description |",
        "|---|---|---|---|---|",
    ]
    for field in layout.preamble_fields:
        out.append(
            f"| `{field.name}` | {_type_column(field)} | {field.offset} | {field.size} | {_escape(field.description)} |"
        )
    out.append("")
    out.append("## `block_header` — universal block header (10 B)")
    out.append("")
    out.append("| Field | Type | Offset | Size | Description |")
    out.append("|---|---|---|---|---|")
    for field in layout.block_header_fields:
        out.append(
            f"| `{field.name}` | {_type_column(field)} | {field.offset} | {field.size} | {_escape(field.description)} |"
        )
    out.append("")
    out.append("## `array_header` — uniform array header (16 B total)")
    out.append("")
    out.append("| Field | Type | Offset | Size | Description |")
    out.append("|---|---|---|---|---|")
    for field in layout.array_header_fields:
        out.append(
            f"| `{field.name}` | {_type_column(field)} | {field.offset} | {field.size} | {_escape(field.description)} |"
        )
    out.append("")
    for block in layout.blocks.values():
        _block_section(out, block)
        out.append("")
    out.append("---")
    out.append("")
    out.append("Block header sizes: " + ", ".join(f"`{b.name}` {b.header_size}" for b in layout.blocks.values()) + ".")
    out.append("")
    return "\n".join(out)
