#!/usr/bin/env python3
"""Emit tests/corpus/manifest.json as a C++ header.

The corpus harness has to read the manifest -- names, sizes, and the block
types each fixture *claims* to cover -- and this repository has no JSON
library and wants none. So the manifest is projected into a header at
configure time, the same arrangement tests/fixtures/build_future_spec.py
already uses for the version-gating fixture: generated, gitignored, and
regenerated whenever the input changes.

Stdlib-only, like the generator and every other tool here. Output is
byte-stable for a given manifest: fixtures are emitted in manifest order and
block lists in their recorded order, so a rebuild with no manifest change
rewrites the same bytes.

The `kind` field distinguishes a whole slide file from a bare block fragment.
Both are legitimate corpus fixtures, but only a slide can be walked from its
file header, so only a slide can have its declared coverage checked
structurally. Absent, `kind` defaults to "slide".
"""
import argparse
import json
import pathlib
import sys

_KINDS = {"slide": "FIXTURE_SLIDE", "fragment": "FIXTURE_FRAGMENT"}


def _c_string(text: str) -> str:
    """A C string literal. Manifest text is ASCII, but escape anyway."""
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def emit(manifest: dict) -> str:
    out = [
        "// Generated by tools/corpus_manifest_header.py from",
        "// tests/corpus/manifest.json -- DO NOT EDIT BY HAND.",
        "//",
        "// The committed manifest is the record of what the corpus contains.",
        "// This is that record in a form C++ can read, so the harness can",
        "// check a fixture still holds what it claims rather than trusting it.",
        "#ifndef IFE_corpus_manifest_hpp",
        "#define IFE_corpus_manifest_hpp",
        "",
        "namespace ife_corpus {",
        "",
        "/// A whole slide file, or a bare block fragment. Only a slide can be",
        "/// walked from its file header, so only a slide's declared coverage",
        "/// can be checked structurally.",
        "enum FixtureKind { FIXTURE_SLIDE, FIXTURE_FRAGMENT };",
        "",
        "struct Fixture {",
        "    const char*        name;",
        "    unsigned long long size;",
        "    const char*        sha256;",
        "    const char*        version;",
        "    FixtureKind        kind;",
        "    /// The block types this fixture claims to cover, nullptr-terminated.",
        "    const char* const* blocks;",
        "};",
        "",
        "namespace detail {",
    ]

    names = list(manifest)
    for index, name in enumerate(names):
        blocks = manifest[name].get("blocks", [])
        literals = ", ".join(_c_string(b) for b in blocks)
        joiner = ", " if literals else ""
        out.append(
            f"inline const char* const blocks_{index}[] = "
            f"{{{literals}{joiner}nullptr}};"
        )

    out += ["}  // namespace detail", "", "inline const Fixture fixtures[] = {"]

    for index, name in enumerate(names):
        entry = manifest[name]
        kind = entry.get("kind", "slide")
        if kind not in _KINDS:
            raise SystemExit(
                f"corpus_manifest_header: {name}: kind {kind!r} is not one of "
                f"{sorted(_KINDS)}"
            )
        out.append(
            "    {"
            f"{_c_string(name)}, "
            f"{entry['size']}ULL, "
            f"{_c_string(entry['sha256'])}, "
            f"{_c_string(str(entry.get('version', '')))}, "
            f"{_KINDS[kind]}, "
            f"detail::blocks_{index}"
            "},"
        )

    out += [
        "};",
        "",
        f"inline constexpr int fixture_count = {len(names)};",
        "",
        "}  // namespace ife_corpus",
        "",
        "#endif  // IFE_corpus_manifest_hpp",
        "",
    ]
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--manifest", required=True, type=pathlib.Path)
    ap.add_argument("--out", required=True, type=pathlib.Path)
    args = ap.parse_args()

    manifest = json.loads(args.manifest.read_text())
    if not manifest:
        raise SystemExit("corpus_manifest_header: the manifest declares no fixtures")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(emit(manifest), encoding="utf-8")
    print(f"corpus_manifest_header: {len(manifest)} fixtures -> {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
