#!/usr/bin/env python3
"""ifc.py — Iris File Compiler.

Schema-driven codegen for the Iris File Extension. Reads a JSON description
of the IFE binary container format and emits five C++ headers consumed by
the FastFHIR substrate (Phase 3 of the substrate migration):

    IFE_DataTypes.hpp        POD reflective structs for sub-block datatypes.
    IFE_VTables.hpp          Per-resource constexpr field offsets / sizes /
                             header_size / recovery_tag.
    IFE_FieldKeys.hpp        constexpr std::array<FieldKey, N> per resource
                             for the reflective reader.
    IFE_Resources.hpp        Single-table dispatch (`ResourceInfo[]` indexed
                             by recovery tag) so the reflective lens needs
                             one table lookup instead of two N-way switches.
    IFE_FieldKeys_wasm.hpp   __EMSCRIPTEN__-gated extern "C" reflection
                             surface (stubs; wired in later phases).

Stdlib-only — no jinja2 dependency. `--check` mode is for CI: regenerate
to a temp directory and diff against the on-disk files; non-zero exit if
anything has drifted from the schema.

Usage
-----
    python3 tools/ifc.py --schema schema/ife_v1.json --out-dir build/generated/IFE
    python3 tools/ifc.py --schema schema/ife_v1.json --out-dir <existing> --check
"""
from __future__ import annotations

import argparse
import filecmp
import json
import os
import shutil
import sys
import tempfile
from pathlib import Path
from typing import Any, Dict, List

# -----------------------------------------------------------------------------
# Type metadata — wire size, natural C++ type, partitioned tag (or UNDEFINED
# for narrow on-wire encodings that don't have a 1:1 IFE::RECOVERY_TAG yet),
# and field kind.
# -----------------------------------------------------------------------------
TYPE_INFO: Dict[str, Dict[str, Any]] = {
    "uint8":     {"size": 1, "cpp": "uint8_t",  "tag": "SCALAR_UINT8",   "kind": "SCALAR"},
    "uint16":    {"size": 2, "cpp": "uint16_t", "tag": "SCALAR_UINT16",  "kind": "SCALAR"},
    "uint24":    {"size": 3, "cpp": "uint32_t", "tag": "UNDEFINED",      "kind": "SCALAR"},
    "uint32":    {"size": 4, "cpp": "uint32_t", "tag": "SCALAR_UINT32",  "kind": "SCALAR"},
    "uint40":    {"size": 5, "cpp": "uint64_t", "tag": "UNDEFINED",      "kind": "SCALAR"},
    "uint64":    {"size": 8, "cpp": "uint64_t", "tag": "SCALAR_UINT64",  "kind": "SCALAR"},
    "int8":      {"size": 1, "cpp": "int8_t",   "tag": "SCALAR_INT8",    "kind": "SCALAR"},
    "int16":     {"size": 2, "cpp": "int16_t",  "tag": "SCALAR_INT16",   "kind": "SCALAR"},
    "int24":     {"size": 3, "cpp": "int32_t",  "tag": "UNDEFINED",      "kind": "SCALAR"},
    "int32":     {"size": 4, "cpp": "int32_t",  "tag": "SCALAR_INT32",   "kind": "SCALAR"},
    "int40":     {"size": 5, "cpp": "int64_t",  "tag": "UNDEFINED",      "kind": "SCALAR"},
    "int64":     {"size": 8, "cpp": "int64_t",  "tag": "SCALAR_INT64",   "kind": "SCALAR"},
    "float16":   {"size": 2, "cpp": "uint16_t", "tag": "UNDEFINED",      "kind": "SCALAR"},
    "float32":   {"size": 4, "cpp": "float",    "tag": "SCALAR_FLOAT32", "kind": "SCALAR"},
    "float64":   {"size": 8, "cpp": "double",   "tag": "SCALAR_FLOAT64", "kind": "SCALAR"},
    "date_time": {"size": 8, "cpp": "uint64_t", "tag": "SCALAR_UINT64",  "kind": "SCALAR"},
}

GENERATED_BANNER = """\
// =============================================================================
// THIS FILE IS GENERATED BY tools/ifc.py — DO NOT EDIT BY HAND.
// Source schema: {schema}
// Regenerate with:
//     python3 tools/ifc.py --schema {schema} --out-dir <build>/generated/IFE
// =============================================================================
"""


def type_info(type_name: str) -> Dict[str, Any]:
    info = TYPE_INFO.get(type_name)
    if info is None:
        raise SystemExit(f"ifc.py: unknown field type {type_name!r}")
    return info


def validate_schema(schema: Dict[str, Any]) -> None:
    """Sanity-check the schema before codegen so failures surface here, not in
    a confusing C++ compile error inside the generated headers."""
    seen_resource_names: set[str] = set()
    seen_datatype_names: set[str] = set()
    for dt in schema.get("datatypes", []):
        if not dt.get("name"):
            raise SystemExit("ifc.py: datatype missing 'name'")
        if dt["name"] in seen_datatype_names:
            raise SystemExit(f"ifc.py: duplicate datatype {dt['name']!r}")
        seen_datatype_names.add(dt["name"])
        seen_field_names: set[str] = set()
        for field in dt.get("fields", []):
            if field["name"] in seen_field_names:
                raise SystemExit(
                    f"ifc.py: duplicate field {field['name']!r} in datatype {dt['name']!r}"
                )
            seen_field_names.add(field["name"])
            type_info(field["type"])
    for res in schema.get("resources", []):
        if not res.get("name"):
            raise SystemExit("ifc.py: resource missing 'name'")
        if res["name"] in seen_resource_names:
            raise SystemExit(f"ifc.py: duplicate resource {res['name']!r}")
        seen_resource_names.add(res["name"])
        if not res.get("recovery_tag", "").startswith("RESOURCE_"):
            raise SystemExit(
                f"ifc.py: resource {res['name']!r} recovery_tag must be a RESOURCE_* tag"
            )
        seen_field_names = set()
        for field in res.get("fields", []):
            if field["name"] in seen_field_names:
                raise SystemExit(
                    f"ifc.py: duplicate field {field['name']!r} in resource {res['name']!r}"
                )
            seen_field_names.add(field["name"])
            type_info(field["type"])


# -----------------------------------------------------------------------------
# IFE_DataTypes.hpp — POD reflective structs for sub-block datatypes.
#
# `wire_size` is pinned (sum of on-disk field sizes). `sizeof(struct)` is NOT
# pinned because narrow on-disk encodings (uint24/uint40) widen to natural
# C++ types in memory — the struct is for reflection, not for direct mmap.
# -----------------------------------------------------------------------------
def gen_data_types(schema: Dict[str, Any], schema_label: str) -> str:
    out: List[str] = []
    out.append(GENERATED_BANNER.format(schema=schema_label))
    out.append("#ifndef IFE_DataTypes_hpp")
    out.append("#define IFE_DataTypes_hpp")
    out.append("")
    out.append("#include <cstddef>")
    out.append("#include <cstdint>")
    out.append("")
    out.append("namespace IFE { namespace datatypes {")
    out.append("")
    for dt in schema["datatypes"]:
        wire_size = sum(type_info(f["type"])["size"] for f in dt["fields"])
        out.append(f"// ---- {dt['name']} (wire_size = {wire_size} bytes) ----")
        out.append(f"struct {dt['name']} {{")
        out.append(f"    static constexpr size_t wire_size = {wire_size};")
        for field in dt["fields"]:
            info = type_info(field["type"])
            out.append(f"    {info['cpp']:<10} {field['name']};")
        out.append(f"}};")
        out.append("")
    out.append("}}  // namespace IFE::datatypes")
    out.append("")
    out.append("#endif  // IFE_DataTypes_hpp")
    out.append("")
    return "\n".join(out)


# -----------------------------------------------------------------------------
# IFE_VTables.hpp — per-resource field offsets, sizes, header_size, recovery_tag.
#
# Replaces the hand-written `enum vtable_sizes` / `enum vtable_offsets` blocks
# in IrisCodecExtension.hpp. Same numeric values; cross-checked by
# tests/ife_codegen_tests.cpp via `static_assert`.
# -----------------------------------------------------------------------------
def gen_vtables(schema: Dict[str, Any], schema_label: str) -> str:
    out: List[str] = []
    out.append(GENERATED_BANNER.format(schema=schema_label))
    out.append("#ifndef IFE_VTables_hpp")
    out.append("#define IFE_VTables_hpp")
    out.append("")
    out.append("#include <cstddef>")
    out.append("")
    out.append('#include "IFE_Types.hpp"')
    out.append("")
    out.append(f"// Schema version pinned at codegen time; build fails if an external")
    out.append(f"// caller has been recompiled against a different schema.")
    out.append(f"namespace IFE {{")
    out.append(
        f"inline constexpr unsigned IFE_SCHEMA_VERSION_MAJOR = {schema['version_major']};"
    )
    out.append(
        f"inline constexpr unsigned IFE_SCHEMA_VERSION_MINOR = {schema['version_minor']};"
    )
    out.append(f"}}  // namespace IFE")
    out.append("")
    out.append("namespace IFE { namespace vtables {")
    out.append("")
    for res in schema["resources"]:
        out.append(f"// ---- {res['name']} ----")
        out.append(f"namespace {res['name']} {{")
        out.append(
            f"    inline constexpr ::IFE::RECOVERY_TAG recovery_tag = "
            f"::IFE::RECOVERY_TAG::{res['recovery_tag']};"
        )
        offset = 0
        out.append("    namespace size {")
        for field in res["fields"]:
            sz = type_info(field["type"])["size"]
            out.append(f"        inline constexpr size_t {field['name']:<24} = {sz};")
        out.append("    }")
        out.append("    namespace offset {")
        for field in res["fields"]:
            out.append(
                f"        inline constexpr size_t {field['name']:<24} = {offset};"
            )
            offset += type_info(field["type"])["size"]
        out.append("    }")
        out.append(f"    inline constexpr size_t header_size = {offset};")
        out.append(f"}}  // namespace {res['name']}")
        out.append("")
    out.append("}}  // namespace IFE::vtables")
    out.append("")
    out.append("#endif  // IFE_VTables_hpp")
    out.append("")
    return "\n".join(out)


# -----------------------------------------------------------------------------
# IFE_FieldKeys.hpp — reflective `FieldKey` arrays per resource.
# -----------------------------------------------------------------------------
def gen_field_keys(schema: Dict[str, Any], schema_label: str) -> str:
    out: List[str] = []
    out.append(GENERATED_BANNER.format(schema=schema_label))
    out.append("#ifndef IFE_FieldKeys_hpp")
    out.append("#define IFE_FieldKeys_hpp")
    out.append("")
    out.append("#include <array>")
    out.append("#include <cstddef>")
    out.append("#include <string_view>")
    out.append("")
    out.append('#include "IFE_Types.hpp"')
    out.append("")
    out.append("namespace IFE {")
    out.append("")
    out.append("// One reflective record per resource field. Phase 6 builder/")
    out.append("// reader walks these arrays to drive read/write of v1 blocks.")
    out.append("struct FieldKey {")
    out.append("    std::string_view name;")
    out.append("    IFE_FieldKind    kind;")
    out.append("    RECOVERY_TAG     scalar_tag;")
    out.append("    std::size_t      offset;")
    out.append("    std::size_t      size;")
    out.append("};")
    out.append("")
    out.append("namespace field_keys {")
    out.append("")
    for res in schema["resources"]:
        n = len(res["fields"])
        out.append(f"// ---- {res['name']} ({n} fields) ----")
        out.append(f"namespace {res['name']} {{")
        out.append(
            f"    inline constexpr std::array<FieldKey, {n}> fields = {{{{"
        )
        offset = 0
        for field in res["fields"]:
            info = type_info(field["type"])
            out.append(
                f'        FieldKey{{"{field["name"]}", '
                f'IFE_FieldKind::{info["kind"]}, '
                f"RECOVERY_TAG::{info['tag']}, "
                f"{offset}, {info['size']}}},"
            )
            offset += info["size"]
        out.append("    }};")
        out.append(f"}}  // namespace {res['name']}")
        out.append("")
    out.append("}  // namespace field_keys")
    out.append("}  // namespace IFE")
    out.append("")
    out.append("#endif  // IFE_FieldKeys_hpp")
    out.append("")
    return "\n".join(out)


# -----------------------------------------------------------------------------
# IFE_Resources.hpp — single dispatch table indexed by RECOVERY_TAG.
#
# Replaces the hand-written N-way switches in IFE_Reflective.hpp that mapped
# (recovery_tag) -> (field_keys span, body_size_hint). With this table the
# reflective lens does one linear scan over a small constexpr array;
# adding a new resource is a pure schema change with zero C++ edits.
# -----------------------------------------------------------------------------
def gen_resources(schema: Dict[str, Any], schema_label: str) -> str:
    out: List[str] = []
    out.append(GENERATED_BANNER.format(schema=schema_label))
    out.append("#ifndef IFE_Resources_hpp")
    out.append("#define IFE_Resources_hpp")
    out.append("")
    out.append("#include <cstddef>")
    out.append("#include <string_view>")
    out.append("")
    out.append('#include "IFE_FieldKeys.hpp"')
    out.append('#include "IFE_Types.hpp"')
    out.append('#include "IFE_VTables.hpp"')
    out.append("")
    out.append("namespace IFE { namespace resources {")
    out.append("")
    out.append("// One reflective record per resource: the tag, its name (string_view")
    out.append("// into a generated literal), the codegen header_size, a pointer to")
    out.append("// the FieldKey array, and its element count. The reflective lens does")
    out.append("// a linear scan over `table` and dispatches off the resulting record.")
    out.append("struct ResourceInfo {")
    out.append("    RECOVERY_TAG     tag;")
    out.append("    std::string_view name;")
    out.append("    std::size_t      header_size;     // includes universal preamble")
    out.append("    const FieldKey*  fields;")
    out.append("    std::size_t      field_count;")
    out.append("};")
    out.append("")
    n = len(schema["resources"])
    out.append(f"inline constexpr std::size_t table_size = {n};")
    out.append(f"inline constexpr ResourceInfo table[{n}] = {{")
    for res in schema["resources"]:
        nm = res["name"]
        fc = len(res["fields"])
        out.append(
            f'    {{RECOVERY_TAG::{res["recovery_tag"]}, "{nm}", '
            f"vtables::{nm}::header_size, "
            f"field_keys::{nm}::fields.data(), {fc}}},"
        )
    out.append("};")
    out.append("")
    out.append("// Linear lookup; the table holds at most a few dozen entries so an")
    out.append("// indexed scan is faster than a hashmap and trivially constexpr.")
    out.append("inline constexpr const ResourceInfo* lookup(RECOVERY_TAG t) noexcept {")
    out.append("    for (std::size_t i = 0; i < table_size; ++i) {")
    out.append("        if (table[i].tag == t) return &table[i];")
    out.append("    }")
    out.append("    return nullptr;")
    out.append("}")
    out.append("")
    out.append("}}  // namespace IFE::resources")
    out.append("")
    out.append("#endif  // IFE_Resources_hpp")
    out.append("")
    return "\n".join(out)


# -----------------------------------------------------------------------------
# IFE_FieldKeys_wasm.hpp — __EMSCRIPTEN__ extern "C" reflection surface.
#
# Stubs only; Phase 6 wires real implementations. The point of generating
# this header now is to keep the JS-visible surface in lockstep with the
# schema instead of hand-maintaining it in two places.
# -----------------------------------------------------------------------------
def gen_field_keys_wasm(schema: Dict[str, Any], schema_label: str) -> str:
    out: List[str] = []
    out.append(GENERATED_BANNER.format(schema=schema_label))
    out.append("#ifndef IFE_FieldKeys_wasm_hpp")
    out.append("#define IFE_FieldKeys_wasm_hpp")
    out.append("")
    out.append("#ifdef __EMSCRIPTEN__")
    out.append("#include <cstddef>")
    out.append("#include <emscripten/emscripten.h>")
    out.append("")
    out.append("// JS-visible reflective surface. Each resource exports two")
    out.append("// entry points: a pointer to the FieldKey array and its count.")
    out.append("// Implementations are provided in Phase 6.")
    out.append('extern "C" {')
    for res in schema["resources"]:
        out.append(
            f"    EMSCRIPTEN_KEEPALIVE const void* IFE_field_keys_{res['name']}();"
        )
        out.append(
            f"    EMSCRIPTEN_KEEPALIVE std::size_t IFE_field_keys_{res['name']}_count();"
        )
    out.append("}  // extern \"C\"")
    out.append("")
    out.append("#endif  // __EMSCRIPTEN__")
    out.append("")
    out.append("#endif  // IFE_FieldKeys_wasm_hpp")
    out.append("")
    return "\n".join(out)


# -----------------------------------------------------------------------------
# Driver
# -----------------------------------------------------------------------------
GENERATORS = {
    "IFE_DataTypes.hpp":      gen_data_types,
    "IFE_VTables.hpp":        gen_vtables,
    "IFE_FieldKeys.hpp":      gen_field_keys,
    "IFE_Resources.hpp":      gen_resources,
    "IFE_FieldKeys_wasm.hpp": gen_field_keys_wasm,
}


def write_outputs(schema: Dict[str, Any], out_dir: Path,
                  schema_label: str) -> List[Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    written: List[Path] = []
    for filename, fn in GENERATORS.items():
        path = out_dir / filename
        path.write_text(fn(schema, schema_label), encoding="utf-8")
        written.append(path)
    return written


def main(argv: List[str]) -> int:
    parser = argparse.ArgumentParser(description="IFE schema-driven codegen.")
    parser.add_argument("--schema", required=True, type=Path,
                        help="Path to the IFE schema JSON.")
    parser.add_argument("--out-dir", required=True, type=Path,
                        help="Directory to write generated headers into.")
    parser.add_argument("--check", action="store_true",
                        help="Verify the on-disk files match what would be regenerated.")
    args = parser.parse_args(argv)

    schema = json.loads(args.schema.read_text(encoding="utf-8"))
    validate_schema(schema)
    # Use just the basename in the generated banner so the comment is stable
    # across different absolute build-tree paths.
    schema_label = args.schema.name

    if args.check:
        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            write_outputs(schema, tmp_path, schema_label)
            mismatches: List[str] = []
            for filename in GENERATORS:
                expected = tmp_path / filename
                actual = args.out_dir / filename
                if not actual.exists() or not filecmp.cmp(expected, actual, shallow=False):
                    mismatches.append(filename)
            if mismatches:
                print(
                    "ifc.py: build-tree generated files are stale: "
                    + ", ".join(mismatches),
                    file=sys.stderr,
                )
                print(
                    "        regenerate with: "
                    f"python3 tools/ifc.py --schema {args.schema} --out-dir {args.out_dir}",
                    file=sys.stderr,
                )
                return 1
            return 0

    written = write_outputs(schema, args.out_dir, schema_label)
    for path in written:
        print(f"ifc.py: wrote {path}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
